[package]
name = "yee-mining2"
version = "0.5.0"
authors = ["YeeCo <contact@yeefoundation.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jsonrpc-core = "10.0.1"
jsonrpc-core-client = "12.1.0"
rand = "0.6.5"
error-chain = "0.12"
futures = "0.1.17"
serde = { version = "1.0", features = ["derive"] }
tokio = "0.1"
log = "0.4"
parking_lot = "0.7.1"
exit-future = "0.1"
codec = { package = "parity-scale-codec", version = "1.3.0", features = ["derive"] }
#yee-runtime = { path = "../../runtime" }
yee-serde-hex = { package = "serde-hex", path = "../../utils/serde-hex" }
yee-rpc = { package = "yee-rpc", path = "../../client/rpc" }
yee-sharding = { package = "yee-sharding", path = "../../client/sharding" }
yee-consensus-pow-primitives = { package = "yee-consensus-pow-primitives", path = "../../primitives/pow" }
yee-consensus-pow = { package = "yc-consensus-pow", path = "../../client/consensus/pow" }
merkle_light = { git = "https://github.com/yeeco/merkle_light.git", branch = "yee-2.0" }
sp-runtime = { package = "sp-runtime", git = "https://github.com/yeeco/substrate.git",  branch = "yee" }
# runtime-primitives = { package = "sr-primitives", git = "https://github.com/yeeco/substrate.git",  branch = "yee", default_features = false, branch = "yee-v1.0" }
yee-primitives = { package = "yp-hrp", path = "../../primitives/hrp" }
