[package]
name = "yee-switch-rpc"
version = "1.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
error-chain = "0.12"
jsonrpc-core = "10.0.1"
jsonrpc-pubsub = "10.0.1"
jsonrpc-derive = "10.0.1"
jsonrpc-core-client = "12.1.0"
jsonrpc-client-transports = "12.1.0"
log = "0.4"
parking_lot = "0.7.1"
serde = { version = "1.0", features = ["derive"] }
impl-serde = { version = "0.1"}
serde_json = "1.0"
codec = { package = "parity-scale-codec", version = "1.3.0", features = ["derive"] }
sp-core = { git = "https://github.com/yeeco/substrate.git", default_features = false, branch = "master"}
sp-std = { version = "2.0.0-dev", git = "https://github.com/yeeco/substrate.git", branch = "master", default-features = false }
sp-runtime = { git = "https://github.com/yeeco/substrate.git", default_features = false, branch = "master"}
#primitives = { package = "substrate-primitives", git = "https://github.com/yeeco/substrate.git", branch = "yee-v1.0" }
#runtime_primitives = { package = "sr-primitives", git = "https://github.com/yeeco/substrate.git", branch = "yee-v1.0" }
#runtime_version = { package = "sr-version", git = "https://github.com/yeeco/substrate.git", branch = "yee-v1.0" }
#substrate-cli = { git = "https://github.com/yeeco/substrate.git", branch = "yee-v1.0" }
#sr-io = { git = "https://github.com/yeeco/substrate.git", branch = "yee-v1.0" }
#yee-runtime = { package = "yee-runtime", path = "../../runtime" }
yee-sharding-primitives= { package = "yee-sharding-primitives", path = "../../primitives/sharding" }
tokio = "0.1.7"
futures = "0.1.17"
hex-literal = "0.1"
rustc-hex = "2.0"
rand = "0.6.5"
num-bigint = "0.2.2"
hex = "0.3.2"
yee-serde-hex = { package = "serde-hex", path = "../../utils/serde-hex" }
yee-primitives = { package = "yp-hrp", path = "../../primitives/hrp" }
yee-sr-primitives = { package = "yee-sr-primitives", path = "../../primitives/srml" }
mining = { package = "yee-mining2", path = "../mining2" }
yee-consensus-pow-primitives = { package = "yee-consensus-pow-primitives", path = "../../primitives/pow" }

[features]
http = []

