[workspace]
members = [
	"bin/node/cli",
	"bootnodes-router",
	"client/cli",
	"dev",
	"switch",
	"utils/build-script-utils"
]

[profile.release]
# Substrate runtime requires unwinding.
panic = "unwind"
