[package]
name = "node-cli"
version = "2.0.0"
authors = ["YeeCo <contact@yeefoundation.com>"]
description = "Yeeroot2 node implementation in Rust."
build = "build.rs"
edition = "2018"
license = "GPL-3.0"
default-run = "yeeroot2"
repository = "https://github.com/yeeco/yeeroot2/"


[package.metadata.wasm-pack.profile.release]
# `wasm-opt` has some problems on linux, see
# https://github.com/rustwasm/wasm-pack/issues/781 etc.
wasm-opt = false

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[badges]
travis-ci = { repository = "paritytech/substrate" }
maintenance = { status = "actively-developed" }
is-it-maintained-issue-resolution = { repository = "paritytech/substrate" }
is-it-maintained-open-issues = { repository = "paritytech/substrate" }

[[bin]]
name = "yeeroot2"
path = "bin/main.rs"
required-features = ["cli"]

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
# third-party dependencies
codec = { package = "parity-scale-codec", default-features = false, features = ["derive"], version = "1.3.0" }
serde = { version = "1.0.102", features = ["derive"] }
futures = { version = "0.3.1", features = ["compat"] }
hex-literal = "0.2.1"
jsonrpc-core = "14.0.3"
log = "0.4.8"
rand = "0.7.2"
structopt = { version = "0.3.8", optional = true }
tracing = "0.1.10"
lazy_static = "1.4.0"
mut_static = "5.0.0"

# primitives
sp-authority-discovery = { version = "2.0.0-dev",  git = "https://github.com/yeeco/substrate.git",  branch = "yee" }
sp-consensus-babe = { version = "0.8.0-dev", git = "https://github.com/yeeco/substrate.git",  branch = "yee" }
grandpa-primitives = { version = "2.0.0-dev", package = "sp-finality-grandpa", git = "https://github.com/yeeco/substrate.git",  branch = "yee" }
sp-core = { version = "2.0.0-dev", git = "https://github.com/yeeco/substrate.git",  branch = "yee" }
sp-runtime = { version = "2.0.0-dev", git = "https://github.com/yeeco/substrate.git",  branch = "yee" }
sp-timestamp = { version = "2.0.0-dev", default-features = false, git = "https://github.com/yeeco/substrate.git",  branch = "yee" }
sp-finality-tracker = { version = "2.0.0-dev", default-features = false, git = "https://github.com/yeeco/substrate.git",  branch = "yee" }
sp-inherents = { version = "2.0.0-dev", git = "https://github.com/yeeco/substrate.git",  branch = "yee" }
sp-keyring = { version = "2.0.0-dev", git = "https://github.com/yeeco/substrate.git",  branch = "yee" }
sp-io = { version = "2.0.0-dev", git = "https://github.com/yeeco/substrate.git",  branch = "yee" }
sp-consensus = { version = "0.8.0-dev", git = "https://github.com/yeeco/substrate.git",  branch = "yee" }
sp-transaction-pool = { version = "2.0.0-dev", git = "https://github.com/yeeco/substrate.git",  branch = "yee" }

# client dependencies
sc-client-api = { version = "2.0.0-dev", git = "https://github.com/yeeco/substrate.git",  branch = "yee" }
sc-client = { version = "0.8.0-dev", git = "https://github.com/yeeco/substrate.git",  branch = "yee" }
yc-client = { path = "../../../client" }
sc-chain-spec = { version = "2.0.0-dev", git = "https://github.com/yeeco/substrate.git",  branch = "yee" }
sc-transaction-pool = { version = "2.0.0-dev", git = "https://github.com/yeeco/substrate.git",  branch = "yee" }
sc-network = { version = "0.8.0-dev", git = "https://github.com/yeeco/substrate.git",  branch = "yee" }
sc-consensus-babe = { version = "0.8.0-dev", git = "https://github.com/yeeco/substrate.git",  branch = "yee" }
grandpa = { version = "0.8.0-dev", package = "sc-finality-grandpa", git = "https://github.com/yeeco/substrate.git",  branch = "yee" }
sc-client-db = { version = "0.8.0-dev", default-features = false, git = "https://github.com/yeeco/substrate.git",  branch = "yee" }
sc-offchain = { version = "2.0.0-dev", git = "https://github.com/yeeco/substrate.git",  branch = "yee" }
sc-rpc = { version = "2.0.0-dev", git = "https://github.com/yeeco/substrate.git",  branch = "yee" }
sc-basic-authorship = { version = "0.8.0-dev", git = "https://github.com/yeeco/substrate.git",  branch = "yee" }
sc-service = { version = "0.8.0-dev", default-features = false, git = "https://github.com/yeeco/substrate.git",  branch = "yee" }
sc-tracing = { version = "2.0.0-dev", git = "https://github.com/yeeco/substrate.git",  branch = "yee" }
sc-telemetry = { version = "2.0.0-dev", git = "https://github.com/yeeco/substrate.git",  branch = "yee" }
sc-authority-discovery = { version = "0.8.0-dev",  git = "https://github.com/yeeco/substrate.git",  branch = "yee" }
#yc-crfg = { path = "../../../client/crfg" }
sc-consensus-pow = { package = "sc-consensus-pow", path = "../../../client/consensus/pow-sc" }

# frame dependencies
pallet-indices = { version = "2.0.0-dev", git = "https://github.com/yeeco/substrate.git",  branch = "yee" }
pallet-timestamp = { version = "2.0.0-dev", default-features = false, git = "https://github.com/yeeco/substrate.git",  branch = "yee" }
pallet-contracts = { version = "2.0.0-dev", git = "https://github.com/yeeco/substrate.git",  branch = "yee" }
frame-system = { version = "2.0.0-dev", git = "https://github.com/yeeco/substrate.git",  branch = "yee" }
pallet-balances = { version = "2.0.0-dev", git = "https://github.com/yeeco/substrate.git",  branch = "yee" }
pallet-transaction-payment = { version = "2.0.0-dev", git = "https://github.com/yeeco/substrate.git",  branch = "yee" }
frame-support = { version = "2.0.0-dev", default-features = false, git = "https://github.com/yeeco/substrate.git",  branch = "yee" }
pallet-im-online = { version = "2.0.0-dev", default-features = false, git = "https://github.com/yeeco/substrate.git",  branch = "yee" }
pallet-authority-discovery = { version = "2.0.0-dev", git = "https://github.com/yeeco/substrate.git",  branch = "yee" }
pallet-staking = { version = "2.0.0-dev", git = "https://github.com/yeeco/substrate.git",  branch = "yee" }

# node-specific dependencies
node-runtime = { version = "2.0.0-dev", git = "https://github.com/yeeco/substrate.git",  branch = "yee" }
node-rpc = { version = "2.0.0-dev", git = "https://github.com/yeeco/substrate.git",  branch = "yee" }
node-primitives = { version = "2.0.0-dev", git = "https://github.com/yeeco/substrate.git",  branch = "yee" }
node-executor = { version = "2.0.0-dev", git = "https://github.com/yeeco/substrate.git",  branch = "yee" }

# CLI-specific dependencies
sc-cli = { version = "0.8.0-dev", optional = true, git = "https://github.com/yeeco/substrate.git",  branch = "yee" }
#yc-cli = { optional = true, path = "../../../client/cli"}
frame-benchmarking-cli = { version = "2.0.0-dev", optional = true, git = "https://github.com/yeeco/substrate.git",  branch = "yee" }
node-transaction-factory = { version = "0.8.0-dev", optional = true, git = "https://github.com/yeeco/substrate.git",  branch = "yee" }
node-inspect = { version = "0.8.0-dev", optional = true, git = "https://github.com/yeeco/substrate.git",  branch = "yee" }

# WASM-specific dependencies
wasm-bindgen = { version = "0.2.57", optional = true }
wasm-bindgen-futures = { version = "0.4.7", optional = true }
browser-utils = { package = "substrate-browser-utils", git = "https://github.com/yeeco/substrate.git",  branch = "yee", optional = true, version = "0.8.0-dev"}

# yee subcommand dependencies
#yee-bootnodes-router = { package = "yee-bootnodes-router", optional = true, path = "../../../bootnodes-router" }
#yee-switch = { package = "yee-switch", optional = true, path = "../../../switch" }

#parity-multiaddr = "0.8.0"
#yee-sharding = { package = "yee-sharding", path = "../../../client/sharding" }
#yee-foreign-network = { package = "yee-foreign-network", path = "../../../foreign/network" }
#yee-relay = { package = "yee-foreign-relay", path = "../../../foreign/relay" }
#yee-dev = { package = "yee-dev", path = "../../../dev" }
#yp-hrp = { package = "yp-hrp", path = "../../../primitives/hrp" }
#yee-pow-primitives = { package = "yee-consensus-pow-primitives", path = "../../../primitives/pow" }
#yp-sharding = { package = "yee-sharding-primitives", path = "../../../primitives/sharding" }
#srml-sharding = { package = "yee-srml-sharding", path = "../../../frame/sharding" }
#srml-crfg = { package = "yee-srml-crfg", path = "../../../frame/crfg" }
#foreign-chain = { package = "yee-foreign-chain", path = "../../../foreign/chain" }
#yee-context = { package = "yee-context", path = "../../../client/context" }

[target.'cfg(target_arch="x86_64")'.dependencies]
node-executor = { version = "2.0.0-dev", git = "https://github.com/yeeco/substrate.git",  branch = "yee", features = [ "wasmtime" ] }
sc-cli = { version = "0.8.0-dev", optional = true, git = "https://github.com/yeeco/substrate.git",  branch = "yee", features = [ "wasmtime" ] }
#yc-cli = { path = "../../../client/cli", optional = true, features = [ "wasmtime" ] }
sc-service = { version = "0.8.0-dev", default-features = false, git = "https://github.com/yeeco/substrate.git",  branch = "yee", features = [ "wasmtime" ] }

[dev-dependencies]
sc-keystore = { version = "2.0.0-dev", git = "https://github.com/yeeco/substrate.git",  branch = "yee" }
sc-consensus-babe = { version = "0.8.0-dev", features = ["test-helpers"], git = "https://github.com/yeeco/substrate.git",  branch = "yee" }
sc-consensus-epochs = { version = "0.8.0-dev", git = "https://github.com/yeeco/substrate.git",  branch = "yee" }
sc-service-test = { version = "2.0.0-dev", git = "https://github.com/yeeco/substrate.git",  branch = "yee" }
futures = "0.3.4"
tempfile = "3.1.0"
assert_cmd = "1.0"
nix = "0.17"
serde_json = "1.0"
regex = "1"
platforms = "0.2.1"

[build-dependencies]
structopt = { version = "0.3.8", optional = true }
node-transaction-factory = { version = "0.8.0-dev", optional = true, git = "https://github.com/yeeco/substrate.git",  branch = "yee" }
node-inspect = { version = "0.8.0-dev", optional = true, git = "https://github.com/yeeco/substrate.git",  branch = "yee" }
frame-benchmarking-cli = { version = "2.0.0-dev", optional = true, git = "https://github.com/yeeco/substrate.git",  branch = "yee" }
#yeeroot-build-script-utils = { path = "../../../utils/build-script-utils", optional = true }
substrate-build-script-utils = { version = "2.0.0-dev", optional = true, git = "https://github.com/yeeco/substrate.git",  branch = "yee" }

[build-dependencies.sc-cli]
version = "0.8.0-dev"
package = "sc-cli"
git = "https://github.com/yeeco/substrate.git"
branch = "yee"
optional = true

[features]
default = [ "cli" ]
browser = [
	"browser-utils",
	"wasm-bindgen",
	"wasm-bindgen-futures",
]
cli = [
    #"codec/std",
	"node-executor/wasmi-errno",
	"node-inspect",
	"node-transaction-factory",
	"sc-cli",
	#"yc-cli",
	"frame-benchmarking-cli",
	"sc-service/db",
	"structopt",
	"substrate-build-script-utils",
    #"yee-bootnodes-router",
    #"yee-switch",
]
runtime-benchmarks = [
	"node-runtime/runtime-benchmarks",
	"frame-benchmarking-cli",
]
