[package]
name = "node-cli"
version = "2.0.0"
authors = ["YeeCo <contact@yeefoundation.com>"]
description = "Yeeroot2 node implementation in Rust."
build = "build.rs"
edition = "2018"
license = "GPL-3.0"
default-run = "yeeroot2"
repository = "https://github.com/yeeco/yeeroot2/"

[package.metadata.wasm-pack.profile.release]
# `wasm-opt` has some problems on linux, see
# https://github.com/rustwasm/wasm-pack/issues/781 etc.
wasm-opt = false

[badges]
travis-ci = { repository = "paritytech/substrate" }
maintenance = { status = "actively-developed" }
is-it-maintained-issue-resolution = { repository = "paritytech/substrate" }
is-it-maintained-open-issues = { repository = "paritytech/substrate" }

[[bin]]
name = "yeeroot2"
path = "bin/main.rs"
required-features = ["cli"]

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
# third-party dependencies
codec = { package = "parity-scale-codec", version = "1.3.0" }
serde = { version = "1.0.102", features = ["derive"] }
futures = { version = "0.3.1", features = ["compat"] }
hex-literal = "0.2.1"
jsonrpc-core = "14.0.3"
log = "0.4.8"
rand = "0.7.2"
structopt = { version = "0.3.8", optional = true }
tracing = "0.1.10"

# primitives
sp-authority-discovery = { package = "sp-authority-discovery", version = "2.0.0-alpha.5", git = "https://github.com/yeeco/substrate.git", branch = "master" }
sp-consensus-babe = { package = "sp-consensus-babe", version = "0.8.0-alpha.5", git = "https://github.com/yeeco/substrate.git", branch = "master" }
grandpa-primitives = { package = "sp-finality-grandpa", version = "2.0.0-alpha.5", git = "https://github.com/yeeco/substrate.git", branch = "master"  }
sp-core = { package = "sp-core", version = "2.0.0-alpha.5", git = "https://github.com/yeeco/substrate.git", branch = "master"  }
sp-runtime = { package = "sp-runtime", version = "2.0.0-alpha.5", git = "https://github.com/yeeco/substrate.git", branch = "master"  }
sp-timestamp = { package = "sp-timestamp", version = "2.0.0-alpha.5", default-features = false, git = "https://github.com/yeeco/substrate.git", branch = "master"  }
sp-finality-tracker = { package = "sp-finality-tracker", version = "2.0.0-alpha.5", default-features = false, git = "https://github.com/yeeco/substrate.git", branch = "master"  }
sp-inherents = { package = "sp-inherents", version = "2.0.0-alpha.5", git = "https://github.com/yeeco/substrate.git", branch = "master"  }
sp-keyring = { package = "sp-keyring", version = "2.0.0-alpha.5", git = "https://github.com/yeeco/substrate.git", branch = "master"  }
sp-io = { package = "sp-io", version = "2.0.0-alpha.5", git = "https://github.com/yeeco/substrate.git", branch = "master" }
sp-consensus = { package = "sp-consensus", version = "0.8.0-alpha.5", git = "https://github.com/yeeco/substrate.git", branch = "master"  }

# client dependencies
sc-client-api = { package = "sc-client-api", version = "2.0.0-alpha.5", git = "https://github.com/yeeco/substrate.git", branch = "master" }
sc-client = { package = "sc-client", version = "0.8.0-alpha.5", git = "https://github.com/yeeco/substrate.git", branch = "master" }
sc-chain-spec = { package = "sc-chain-spec", version = "2.0.0-alpha.5", git = "https://github.com/yeeco/substrate.git", branch = "master" }
sc-transaction-pool = { package = "sc-transaction-pool", version = "2.0.0-alpha.5", git = "https://github.com/yeeco/substrate.git", branch = "master" }
sp-transaction-pool = { package = "sp-transaction-pool", version = "2.0.0-alpha.5", git = "https://github.com/yeeco/substrate.git", branch = "master" }
sc-network = { package = "sc-network", version = "0.8.0-alpha.5", git = "https://github.com/yeeco/substrate.git", branch = "master" }
sc-consensus-babe = { package = "sc-consensus-babe", version = "0.8.0-alpha.5", git = "https://github.com/yeeco/substrate.git", branch = "master" }
grandpa = { version = "0.8.0-alpha.5", package = "sc-finality-grandpa", git = "https://github.com/yeeco/substrate.git", branch = "master" }
sc-client-db = { package = "sc-client-db", version = "0.8.0-alpha.5", default-features = false , git = "https://github.com/yeeco/substrate.git", branch = "master" }
sc-offchain = { package = "sc-offchain", version = "2.0.0-alpha.5", git = "https://github.com/yeeco/substrate.git", branch = "master"  }
sc-rpc = { package = "sc-rpc", version = "2.0.0-alpha.5", git = "https://github.com/yeeco/substrate.git", branch = "master" }
sc-basic-authorship = { package = "sc-basic-authorship", version = "0.8.0-alpha.5", git = "https://github.com/yeeco/substrate.git", branch = "master" }
sc-service = { package = "sc-service", version = "0.8.0-alpha.5", default-features = false, git = "https://github.com/yeeco/substrate.git", branch = "master" }
sc-tracing = { package = "sc-tracing", version = "2.0.0-alpha.5", git = "https://github.com/yeeco/substrate.git", branch = "master" }
sc-telemetry = { package = "sc-telemetry", version = "2.0.0-alpha.5", git = "https://github.com/yeeco/substrate.git", branch = "master" }
sc-authority-discovery = { package = "sc-authority-discovery", version = "0.8.0-alpha.5", git = "https://github.com/yeeco/substrate.git", branch = "master" }

# yee subcommand dependencies
yee-bootnodes-router = { package = "yee-bootnodes-router", path = "../../../bootnodes-router"}
yee-switch = { package = "yee-switch", path = "../../../switch" }

# frame dependencies
pallet-indices = { package = "pallet-indices", version = "2.0.0-alpha.5", git = "https://github.com/yeeco/substrate.git", branch = "master" }
pallet-timestamp = { package = "pallet-timestamp", version = "2.0.0-alpha.5", default-features = false, git = "https://github.com/yeeco/substrate.git", branch = "master" }
pallet-contracts = { package = "pallet-contracts", version = "2.0.0-alpha.5", git = "https://github.com/yeeco/substrate.git", branch = "master" }
frame-system = { package = "frame-system", version = "2.0.0-alpha.5", git = "https://github.com/yeeco/substrate.git", branch = "master" }
pallet-balances = { package = "pallet-balances", version = "2.0.0-alpha.5", git = "https://github.com/yeeco/substrate.git", branch = "master" }
pallet-transaction-payment = { package = "pallet-transaction-payment", version = "2.0.0-alpha.5", git = "https://github.com/yeeco/substrate.git", branch = "master" }
frame-support = { package = "frame-support", version = "2.0.0-alpha.5", default-features = false, git = "https://github.com/yeeco/substrate.git", branch = "master" }
pallet-im-online = { package = "pallet-im-online", version = "2.0.0-alpha.5", default-features = false, git = "https://github.com/yeeco/substrate.git", branch = "master" }
pallet-authority-discovery = { package = "pallet-authority-discovery", version = "2.0.0-alpha.5", git = "https://github.com/yeeco/substrate.git", branch = "master" }
pallet-staking = { package = "pallet-staking", version = "2.0.0-alpha.5", git = "https://github.com/yeeco/substrate.git", branch = "master" }

# node-specific dependencies
node-runtime = { package = "node-runtime", version = "2.0.0-alpha.5", git = "https://github.com/yeeco/substrate.git", branch = "master" }
node-rpc = { package = "node-rpc", version = "2.0.0-alpha.5", git = "https://github.com/yeeco/substrate.git", branch = "master" }
node-primitives = { package = "node-primitives", version = "2.0.0-alpha.5", git = "https://github.com/yeeco/substrate.git", branch = "master"  }
node-executor = { package = "node-executor", version = "2.0.0-alpha.5", git = "https://github.com/yeeco/substrate.git", branch = "master"  }

# CLI-specific dependencies
yc-cli = { package = "yc-cli", optional = true, path = "../../../client/cli" }
#sc-cli = { package = "sc-cli", version = "0.8.0-alpha.5", optional = true, git = "https://github.com/yeeco/substrate.git", branch = "master" }
frame-benchmarking-cli = { package = "frame-benchmarking-cli", version = "2.0.0-alpha.5", optional = true, git = "https://github.com/yeeco/substrate.git", branch = "master" }
node-transaction-factory = { package = "node-transaction-factory", version = "0.8.0-alpha.5", optional = true, git = "https://github.com/yeeco/substrate.git", branch = "master" }
node-inspect = { package = "node-inspect", version = "0.8.0-alpha.5", optional = true, git = "https://github.com/yeeco/substrate.git", branch = "master"  }

# WASM-specific dependencies
wasm-bindgen = { version = "0.2.57", optional = true }
wasm-bindgen-futures = { version = "0.4.7", optional = true }
browser-utils = { package = "substrate-browser-utils", optional = true, version = "0.8.0-alpha.5", git = "https://github.com/yeeco/substrate.git", branch = "master" }

[target.'cfg(target_arch="x86_64")'.dependencies]
node-executor = { package = "node-executor", version = "2.0.0-alpha.4", features = [ "wasmtime" ], git = "https://github.com/yeeco/substrate.git", branch = "master" }
sc-cli = { package = "sc-cli", version = "0.8.0-alpha.4", optional = true, features = [ "wasmtime" ], git = "https://github.com/yeeco/substrate.git", branch = "master" }
sc-service = { package = "sc-service", version = "0.8.0-alpha.4", default-features = false, features = [ "wasmtime" ], git = "https://github.com/yeeco/substrate.git", branch = "master" }

[dev-dependencies]
sc-keystore = { package = "sc-keystore", version = "2.0.0-alpha.5", git = "https://github.com/yeeco/substrate.git", branch = "master"  }
sc-consensus-babe = { package = "sc-consensus-babe", version = "0.8.0-alpha.5", features = ["test-helpers"], git = "https://github.com/yeeco/substrate.git", branch = "master" }
sc-consensus-epochs = { package = "sc-consensus-epochs", version = "0.8.0-alpha.5", git = "https://github.com/yeeco/substrate.git", branch = "master" }
sc-service-test = { package = "sc-service-test", version = "2.0.0-dev", git = "https://github.com/yeeco/substrate.git", branch = "master" }
futures = "0.3.4"
tempfile = "3.1.0"
assert_cmd = "1.0"
nix = "0.17"
serde_json = "1.0"

[build-dependencies]
yeeroot-build-script-utils = { package = "yeeroot-build-script-utils", path = "../../../utils/build-script-utils"}
substrate-build-script-utils = { version = "2.0.0-alpha.5", package = "substrate-build-script-utils", git = "https://github.com/yeeco/substrate.git", branch = "master" }
structopt = { version = "0.3.8", optional = true }
node-transaction-factory = { package = "node-transaction-factory", version = "0.8.0-alpha.5", optional = true, git = "https://github.com/yeeco/substrate.git", branch = "master" }
node-inspect = { package = "node-inspect", version = "0.8.0-alpha.5", optional = true, git = "https://github.com/yeeco/substrate.git", branch = "master" }
frame-benchmarking-cli = { package = "frame-benchmarking-cli", version = "2.0.0-alpha.5", optional = true, git = "https://github.com/yeeco/substrate.git", branch = "master" }
yee-bootnodes-router = { package = "yee-bootnodes-router", path = "../../../bootnodes-router", optional = true }
yee-switch = { package = "yee-switch", path = "../../../switch", optional = true }


[build-dependencies.yc-cli]
package = "yc-cli"
path = "../../../client/cli"
optional = true

[build-dependencies.vergen]
version = "3.0.4"
optional = true

[features]
default = [ "cli" ]
browser = [
	"browser-utils",
	"wasm-bindgen",
	"wasm-bindgen-futures",
]
cli = [
	"node-executor/wasmi-errno",
	"node-inspect",
	"node-transaction-factory",
	"yc-cli",
	"frame-benchmarking-cli",
	"sc-service/rocksdb",
	"structopt",
	"vergen",
	"yee-bootnodes-router",
	"yee-switch",
]
runtime-benchmarks = [ "node-runtime/runtime-benchmarks" ]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
