[package]
name = "yee-sharding-primitives"
version = "0.1.0"
authors = ["YeeCo <contact@yeefoundation.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
codec = { package = "parity-scale-codec", version = "1.3.0", features = ["derive"] }
sp-core = { git = "https://github.com/yeeco/substrate.git", default_features = false, branch = "master"}
sp-runtime = { git = "https://github.com/yeeco/substrate.git", default_features = false, branch = "master"}
#sc-client = { git = "https://github.com/yeeco/substrate.git", default_features = false, branch = "master"}

#primitives = { package = "substrate-primitives", git = "https://github.com/yeeco/substrate.git", default_features = false, branch = "yee-v1.0" }
#runtime_primitives = { package = "sr-primitives", git = "https://github.com/yeeco/substrate.git", default_features = false, branch = "yee-v1.0" }
#substrate-client = { git = "https://github.com/yeeco/substrate.git", default_features = false, branch = "yee-v1.0" }
#parity-codec = { version = "3.2", default-features = false, features = ["derive"] }

[dev-dependencies]
#yee-runtime = { package = "yee-runtime", path = "../../../runtime" }
hex = "0.3.1"
yee-primitives = { package = "yp-hrp", path = "../../primitives/hrp" }
rand = "0.6.5"
schnorrkel = "0.9"

[features]
default = ["std"]
std = [
    "sp-core/std",
    "sp-runtime/std",
#    "sc-client/std",
    "codec/std",
]
