[package]
name = "yc-consensus-pow"
version = "0.1.0"
authors = ["YeeCo <contact@yeefoundation.com>"]
edition = "2018"

[dependencies]
futures = "0.1"
log = "0.4"
parking_lot = "0.10.0"
tokio = "0.1"
serde = { version = "1.0", optional = true, features = ["derive"] }
pow_primitives = { package = "yee-consensus-pow-primitives", path = "../../../primitives/pow" }
sc-client-api = { package = "sc-client-api", git = "https://github.com/yeeco/substrate.git",  branch = "yee" }
sp-runtime = { package = "sp-runtime", git = "https://github.com/yeeco/substrate.git",  branch = "yee" }
sp-blockchain = { package = "sp-blockchain", git = "https://github.com/yeeco/substrate.git",  branch = "yee" }
sp-arithmetic = { version = "2.0.0-dev", git = "https://github.com/yeeco/substrate.git",  branch = "yee" }
sp-consensus = { package = "sp-consensus", git = "https://github.com/yeeco/substrate.git",  branch = "yee" }
sp-inherents = { package = "sp-inherents", git = "https://github.com/yeeco/substrate.git",  branch = "yee" }
sp-core = { package = "sp-core", git = "https://github.com/yeeco/substrate.git",  branch = "yee" }
sp-api = { git = "https://github.com/yeeco/substrate.git",  branch = "yee" }
sp-state-machine = { git = "https://github.com/yeeco/substrate.git",  branch = "yee" }
codec = { package = "parity-scale-codec", version = "1.3.0", features = ["derive"] }
#
#pallet-timestamp = { package = "pallet-timestamp", git = "https://github.com/yeeco/substrate.git",  branch = "yee" }
merkle_light = { git = "https://github.com/yeeco/merkle_light.git", branch = "yee-2.0" }
yee-sharding = { package = "yee-sharding", path = "../../sharding" }
yee-sharding-primitives = { package = "yee-sharding-primitives", path = "../../../primitives/sharding" }
#foreign_chain = { package = "yee-foreign-chain", path = "../../../foreign/chain" }
#yc-client = { path = "../../" }

yee-srml-pow = { path = "../../../frame/pow" }
yee-merkle = { path = "../../util/merkle" }
#yee-srml-executive = { path = "../../../frame/executive" }
##yee-runtime = { package = "yee-runtime", path = "../../../runtime" }
yee-context = { package = "yee-context", path = "../../context" }
#util = { package = "util", path = "../../util" }
hash-db = { version = "0.15.2", default-features = false }
ansi_term = "0.11"
#primitive-types = { version = "0.7.0", default-features = false, features = ["codec"] }

[dev-dependencies]
hex-literal = "0.2"
hex = "0.3.1"

[features]
default = ["std"]
std = [
	"serde",
]
