[package]
name = "yee-consensus-pow"
version = "0.1.0"
authors = ["YeeCo <contact@yeefoundation.com>"]
edition = "2018"

[dependencies]
futures = "0.1"
log = "0.4"
#parity-codec = "3.5"
#parking_lot = "0.7.1"
#tokio = "0.1"
serde = { version = "1.0", optional = true, features = ["derive"] }
#pow_primitives = { package = "yee-consensus-pow-primitives", path = "../../../primitives/pow" }
#yee-srml-pow = { path = "../../../frame/pow" }
#sc-client-api = { package = "sc-client-api", git = "https://github.com/yeeco/substrate.git", branch = "master" }
#sp-runtime = { package = "sp-runtime", git = "https://github.com/yeeco/substrate.git", branch = "master" }
#sp-blockchain = { package = "sp-blockchain", git = "https://github.com/yeeco/substrate.git", branch = "master" }
#sp-consensus = { package = "sp-consensus", git = "https://github.com/yeeco/substrate.git", branch = "master" }
#sp-inherents = { package = "sp-inherents", git = "https://github.com/yeeco/substrate.git", branch = "master" }
#sp-core = { package = "sp-core", git = "https://github.com/yeeco/substrate.git", branch = "master" }
#codec = { package = "parity-scale-codec", version = "1.3.0", default-features = false, features = ["derive"] }
#
#pallet-timestamp = { package = "pallet-timestamp", git = "https://github.com/yeeco/substrate.git", branch = "master" }
#merkle_light = { git = "https://github.com/yeeco/merkle_light.git", branch = "yee" }
#yee-sharding = { package = "yee-sharding", path = "../../sharding" }
#yee-sharding-primitives = { package = "yee-sharding-primitives", path = "../../../primitives/sharding" }
#foreign_chain = { package = "yee-foreign-chain", path = "../../../foreign/chain" }
#yee-merkle = { path = "../../util/merkle" }
#yee-srml-executive = { path = "../../../frame/executive" }
##yee-runtime = { package = "yee-runtime", path = "../../../runtime" }
#yee-context = { package = "yee-context", path = "../../context" }
#util = { package = "util", path = "../../util" }
#hash-db = "0.12"
#ansi_term = "0.11"
#primitive-types = { version = "0.7.0", default-features = false, features = ["codec"] }


#primitives = { package = "substrate-primitives", git = "https://github.com/yeeco/substrate.git", branch = "yee-v1.0" }
#runtime_primitives = { package = "sr-primitives", git = "https://github.com/yeeco/substrate.git", branch = "yee-v1.0" }
#srml-timestamp = { git = "https://github.com/yeeco/substrate.git", branch = "yee-v1.0" }
#substrate-service = { git = "https://github.com/yeeco/substrate.git", branch = "yee-v1.0" }
#serde = { version = "1.0", optional = true, features = ["derive"] }
#merkle_light = { git = "https://github.com/yeeco/merkle_light.git", branch = "yee" }

[dev-dependencies]
hex-literal = "0.2"
hex = "0.3.1"

[features]
default = ["std"]
std = [
	"serde",
]
