[package]
name = "yee-rpc"
version = "0.1.0"
authors = ["YeeCo <contact@yeefoundation.com>"]
edition = "2018"

[dependencies]
error-chain = "0.12"
#substrate-rpc-services = { package = "substrate-rpc-servers", git = "https://github.com/yeeco/substrate.git", branch = "yee-v1.0" }
#runtime_primitives = { package = "sr-primitives", git = "https://github.com/yeeco/substrate.git", branch = "yee-v1.0" }
#substrate-service = { git = "https://github.com/yeeco/substrate.git", branch = "yee-v1.0" }
#client = { package = "substrate-client", git = "https://github.com/yeeco/substrate.git", branch = "yee-v1.0" }
#network = { package = "substrate-network", git = "https://github.com/yeeco/substrate.git", branch = "yee-v1.0" }
#transaction_pool = { package = "substrate-transaction-pool", git = "https://github.com/yeeco/substrate.git", branch = "yee-v1.0" }
#consensus_common = { package = "substrate-consensus-common", git = "https://github.com/yeeco/substrate.git", branch = "yee-v1.0" }
#tokio = "0.1"
#pubsub = { package = "jsonrpc-pubsub", version = "10.0.1" }
#jsonrpc-derive = "10.0.2"
#jsonrpc-core = "10.0.1"
#substrate-rpc = { package = "substrate-rpc", git = "https://github.com/yeeco/substrate.git", branch = "yee-v1.0"}
#basic-authorship = { package = "substrate-basic-authorship", git = "https://github.com/yeeco/substrate.git", branch = "yee-v1.0" }
#substrate-primitives = { package = "substrate-primitives", git = "https://github.com/yeeco/substrate.git", branch = "yee-v1.0" }
#serde = { version = "1.0", features = ["derive"] }
#yee-runtime = { package = "node-runtime", git = "https://github.com/yeeco/substrate.git", branch = "master" }
#yee-consensus-pow = { package = "yee-consensus-pow", path = "../../client/consensus/pow" }
#yee-consensus-pow-primitives = { package = "yee-consensus-pow-primitives", path = "../../primitives/pow" }
parking_lot = "0.7.1"
log = "0.4"
#parity-codec = "3.5"
yee-serde-hex = { package = "serde-hex", path = "../../utils/serde-hex" }
