[package]
name = "yee-sr-primitives"
version = "0.4.0"
authors = ["YeeCo <contact@yeefoundation.com>"]
edition = "2018"

[dependencies]
codec = { package = "parity-scale-codec", version = "1.3.0", features = ["derive"] }
sp-core = { git = "https://github.com/yeeco/substrate.git", default_features = false, branch = "master"}
sp-std = { version = "2.0.0-dev", git = "https://github.com/yeeco/substrate.git", branch = "master", default-features = false }
sp-runtime = { git = "https://github.com/yeeco/substrate.git", default_features = false, branch = "master"}
#rstd = { package = "sr-std", git = "https://github.com/yeeco/substrate.git", branch = "yee-v1.0", default-features = false }
#parity-codec = { version = "3.5", default-features = false, features = ["derive"] }
#substrate-primitives = { package = "substrate-primitives", git = "https://github.com/yeeco/substrate.git", branch = "yee-v1.0", default-features = false }
#substrate-sr-primitives = { package = "sr-primitives", git = "https://github.com/yeeco/substrate.git", branch = "yee-v1.0", default-features = false }


[features]
default = ["std"]
std = [
    "sp-std/std",
	"codec/std",
]
