[package]
name = "yeeroot-build-script-utils"
version = "0.1.0"
authors = ["YeeCo <contact@yeefoundation.com>"]
edition = "2018"
license = "GPL-3.0"
description = "Crate with utility functions for `build.rs` scripts."

[dependencies]
platforms = "0.2.1"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
