[package]
name = "yp-consensus-pow"
version = "0.1.0"
authors = ["YeeCo <contact@yeefoundation.com>"]
edition = "2018"

[dependencies]
sp-core = { git = "https://github.com/yeeco/substrate.git", default_features = false, branch = "yee" }
sp-runtime = {  git = "https://github.com/yeeco/substrate.git", default_features = false, branch = "yee" }
sp-api = { git = "https://github.com/yeeco/substrate.git", default_features = false, branch = "yee"  }
sp-std = { git = "https://github.com/yeeco/substrate.git", default_features = false, branch = "yee" }
sp-inherents = { git = "https://github.com/yeeco/substrate.git", default_features = false, branch = "yee" }
sp-timestamp = { git = "https://github.com/yeeco/substrate.git", default_features = false, branch = "yee" }
codec = { package = "parity-scale-codec", version = "1.3.0", default-features = false, features = ["derive"] }
serde = { version = "1.0", optional = true }

[features]
default = ["std"]
std = [
    "serde",
    "sp-core/std",
    "sp-runtime/std",
]
