[package]
authors = ['Anonymous']
edition = '2018'
name = 'pallet-template'
version = "2.0.0-dev"
license = "Unlicense"
description = "FRAME pallet template"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "1.3.0", default-features = false, features = ["derive"] }

[dependencies.frame-support]
default-features = false
version = "2.0.0-dev"
git = "https://github.com/yeeco/substrate.git"
branch = "yee"

[dependencies.frame-system]
default-features = false
version = "2.0.0-dev"
git = "https://github.com/yeeco/substrate.git"
branch = "yee"
[dev-dependencies.sp-core]
default-features = false
version = "2.0.0-dev"
git = "https://github.com/yeeco/substrate.git"
branch = "yee"

[dev-dependencies.sp-io]
default-features = false
version = "2.0.0-dev"
git = "https://github.com/yeeco/substrate.git"
branch = "yee"

[dev-dependencies.sp-runtime]
default-features = false
version = "2.0.0-dev"
git = "https://github.com/yeeco/substrate.git"
branch = "yee"


[features]
default = ['std']
std = [
	'codec/std',
	'frame-support/std',
	'frame-system/std'
]
